# MIT Licence
# Copyright 2026 feraxhp

name: Publish Web App
run-name: 🚀 Publish Web App 🚀
on:
    workflow_dispatch:
    push:
      tags:
        - 'v*'

permissions:
    contents: read
    pages: write
    id-token: write
  
concurrency:
    group: "pages"
    cancel-in-progress: false
  
jobs:
  sample:
    name: 📟 Deploy 2 pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:

      - name: 🗃️ Checkout code
        uses: actions/checkout@v4
      
      - name: 📦 Install npm dependencies
        shell: bash
        run: npm install
      
      - name: 🧩 Build fractos
        shell: bash
        run: npm run build

      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "app/home/dist"

      - name: 📡 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: 🎉 Congratulations 🎉
        run: |
          echo "Your page is Up"
          echo "🎉 Congratulations 🎉"

# See LICENCE in the project root
# for the full licence detail.